<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $newTemplates = [
            [
                'name' => 'Fresher Resume',
                'slug' => 'fresher-green',
                'preview_image_path' => 'templates/fresher-green.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'fresher',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Dark Navy & Gold',
                'slug' => 'dark-navy',
                'preview_image_path' => 'templates/dark-navy.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'executive',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Purple Gradient Modern',
                'slug' => 'purple-gradient',
                'preview_image_path' => 'templates/purple-gradient.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'modern',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Teal Split Sidebar',
                'slug' => 'teal-sidebar',
                'preview_image_path' => 'templates/teal-sidebar.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'professional',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Orange Impact',
                'slug' => 'orange-impact',
                'preview_image_path' => 'templates/orange-impact.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'creative',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Red Executive',
                'slug' => 'red-executive',
                'preview_image_path' => 'templates/red-executive.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'executive',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Swiss Minimal White',
                'slug' => 'minimal-white',
                'preview_image_path' => 'templates/minimal-white.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'minimal',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Blue Corporate Elite',
                'slug' => 'blue-corporate',
                'preview_image_path' => 'templates/blue-corporate.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'corporate',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Rose Creative Designer',
                'slug' => 'rose-creative',
                'preview_image_path' => 'templates/rose-creative.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'creative',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Tech & Developer Monospace',
                'slug' => 'tech-developer',
                'preview_image_path' => 'templates/tech-developer.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'technical',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Classic Academic Serif',
                'slug' => 'classic-serif',
                'preview_image_path' => 'templates/classic-serif.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'academic',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Infographic Metric Bars',
                'slug' => 'infographic-bars',
                'preview_image_path' => 'templates/infographic-bars.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'modern',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Timeline Modern Flow',
                'slug' => 'timeline-modern',
                'preview_image_path' => 'templates/timeline-modern.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'modern',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Golden Luxury Prestige',
                'slug' => 'golden-luxury',
                'preview_image_path' => 'templates/golden-luxury.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'executive',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
        ];

        foreach ($newTemplates as $t) {
            DB::table('cv_templates')->updateOrInsert(
                ['slug' => $t['slug']],
                array_merge($t, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }

    public function down(): void
    {
        DB::table('cv_templates')->whereIn('slug', [
            'fresher-green',
            'dark-navy',
            'purple-gradient',
            'teal-sidebar',
            'orange-impact',
            'red-executive',
            'minimal-white',
            'blue-corporate',
            'rose-creative',
            'tech-developer',
            'classic-serif',
            'infographic-bars',
            'timeline-modern',
            'golden-luxury',
        ])->delete();
    }
};
