<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $templates = [
            [
                'name' => 'Sleek Financial Consultant Bio',
                'slug' => 'sleek-financial',
                'preview_image_path' => 'templates/sleek-financial.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'executive',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Architect Manager',
                'slug' => 'architect-manager',
                'preview_image_path' => 'templates/architect-manager.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'professional',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Teacher Resume',
                'slug' => 'teacher-resume',
                'preview_image_path' => 'templates/teacher-resume.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'academic',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Project Manager Resume',
                'slug' => 'project-manager',
                'preview_image_path' => 'templates/project-manager.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'executive',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Journalist Photographer Resume',
                'slug' => 'journalist-photographer',
                'preview_image_path' => 'templates/journalist-photographer.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'creative',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Fashion Designer Resume',
                'slug' => 'fashion-designer',
                'preview_image_path' => 'templates/fashion-designer.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'creative',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Social Media Manager Resume',
                'slug' => 'social-media-manager',
                'preview_image_path' => 'templates/social-media-manager.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'modern',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Developer Resume',
                'slug' => 'developer-resume',
                'preview_image_path' => 'templates/developer-resume.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'technical',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Interior Design Resume',
                'slug' => 'interior-design',
                'preview_image_path' => 'templates/interior-design.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'creative',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Sales Manager Resume',
                'slug' => 'sales-manager',
                'preview_image_path' => 'templates/sales-manager.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'professional',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Analyst Resume',
                'slug' => 'analyst-resume',
                'preview_image_path' => 'templates/analyst-resume.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'professional',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Photographer Resume',
                'slug' => 'photographer-resume',
                'preview_image_path' => 'templates/photographer-resume.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'creative',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Graphic Designer Resume',
                'slug' => 'graphic-designer',
                'preview_image_path' => 'templates/graphic-designer.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'creative',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Manager Resume',
                'slug' => 'manager-pastel',
                'preview_image_path' => 'templates/manager-pastel.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'modern',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Business Analyst Resume',
                'slug' => 'business-analyst',
                'preview_image_path' => 'templates/business-analyst.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'professional',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Business Administrator Resume',
                'slug' => 'business-administrator',
                'preview_image_path' => 'templates/business-administrator.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'professional',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'Social Media Specialist Resume',
                'slug' => 'social-media-specialist',
                'preview_image_path' => 'templates/social-media-specialist.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'modern',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => false,
                'credits_required' => 0,
                'html_content' => null,
            ],
            [
                'name' => 'UI UX Developer Resume',
                'slug' => 'ui-ux-developer',
                'preview_image_path' => 'templates/ui-ux-developer.png',
                'is_premium' => false,
                'price' => 0,
                'category' => 'technical',
                'is_active' => true,
                'is_ats_friendly' => true,
                'ats_compatible' => true,
                'is_featured' => true,
                'credits_required' => 0,
                'html_content' => null,
            ],
        ];

        foreach ($templates as $t) {
            DB::table('cv_templates')->updateOrInsert(
                ['slug' => $t['slug']],
                array_merge($t, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }

    public function down(): void
    {
        DB::table('cv_templates')->whereIn('slug', [
            'sleek-financial',
            'architect-manager',
            'teacher-resume',
            'project-manager',
            'journalist-photographer',
            'fashion-designer',
            'social-media-manager',
            'developer-resume',
            'interior-design',
            'sales-manager',
            'analyst-resume',
            'photographer-resume',
            'graphic-designer',
            'manager-pastel',
            'business-analyst',
            'business-administrator',
            'social-media-specialist',
            'ui-ux-developer',
        ])->delete();
    }
};
