<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Cache;
use App\Models\User;
use App\Models\Category;
use App\Models\Company;
use App\Models\Job;
use App\Models\CvTemplate;

return new class extends Migration
{
    public function up(): void
    {
        // 0. Ensure categories has is_highlighted column
        if (!Schema::hasColumn('categories', 'is_highlighted')) {
            Schema::table('categories', function (Blueprint $table) {
                $table->boolean('is_highlighted')->default(true)->after('is_active');
            });
        }

        // 1. Categories
        $categoriesData = [
            ['name_en' => 'Software & IT', 'name_bn' => 'সফটওয়্যার ও আইটি', 'icon' => 'code', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Banking & Finance', 'name_bn' => 'ব্যাংকিং ও ফাইন্যান্স', 'icon' => 'calculator', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Marketing & Sales', 'name_bn' => 'মার্কেটিং ও সেলস', 'icon' => 'trending-up', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Customer Support', 'name_bn' => 'কাস্টমার সাপোর্ট', 'icon' => 'users', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Garments & Textile', 'name_bn' => 'গার্মেন্টস ও টেক্সটাইল', 'icon' => 'building-2', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Healthcare & Pharma', 'name_bn' => 'স্বাস্থ্য ও ফার্মাসিউটিক্যালস', 'icon' => 'heart', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Education & Training', 'name_bn' => 'শিক্ষা ও প্রশিক্ষণ', 'icon' => 'graduation-cap', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Design & Creative', 'name_bn' => 'ডিজাইন ও ক্রিয়েটিভ', 'icon' => 'palette', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Engineering', 'name_bn' => 'ইঞ্জিনিয়ারিং', 'icon' => 'cpu', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Remote & Freelance', 'name_bn' => 'রিমোট ও ফ্রিল্যান্সিং', 'icon' => 'wifi', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Telecommunication', 'name_bn' => 'টেলিকমিউনিকেশন', 'icon' => 'smartphone', 'is_highlighted' => true, 'is_active' => true],
            ['name_en' => 'Logistics & Supply Chain', 'name_bn' => 'লজিস্টিকস ও সাপ্লাই চেইন', 'icon' => 'layers', 'is_highlighted' => true, 'is_active' => true],
        ];

        $catMap = [];
        foreach ($categoriesData as $c) {
            $cat = Category::firstOrCreate(
                ['name_en' => $c['name_en']],
                [
                    'name_bn' => $c['name_bn'],
                    'icon' => $c['icon'],
                    'is_highlighted' => $c['is_highlighted'],
                    'is_active' => $c['is_active'],
                ]
            );
            $cat->update([
                'name_bn' => $c['name_bn'],
                'icon' => $c['icon'],
                'is_highlighted' => true,
                'is_active' => true,
            ]);
            $catMap[$c['name_en']] = $cat->id;
        }

        // 2. Companies & Employer Users
        $companiesData = [
            [
                'name' => 'Brain Station 23',
                'slug' => 'brain-station-23',
                'industry' => 'Software & IT Services',
                'location' => 'Mohakhali, Dhaka',
                'city' => 'Dhaka',
                'description' => 'Brain Station 23 is a leading software development company in Bangladesh specializing in Enterprise solutions, Fintech, Cloud, and AI.',
                'website' => 'https://brainstation-23.com',
                'email' => 'careers@brainstation-23.com',
                'is_featured' => true,
            ],
            [
                'name' => 'bKash Limited',
                'slug' => 'bkash-limited',
                'industry' => 'Fintech & MFS',
                'location' => 'Gulshan, Dhaka',
                'city' => 'Dhaka',
                'description' => 'bKash is Bangladesh’s largest mobile financial service provider, empowering millions with seamless digital transactions.',
                'website' => 'https://www.bkash.com',
                'email' => 'hr@bkash.com',
                'is_featured' => true,
            ],
            [
                'name' => 'Pathao',
                'slug' => 'pathao',
                'industry' => 'Logistics & Tech Platform',
                'location' => 'Banani, Dhaka',
                'city' => 'Dhaka',
                'description' => 'Pathao is the fastest growing tech platform in Bangladesh providing ride-sharing, food delivery, and courier services.',
                'website' => 'https://pathao.com',
                'email' => 'jobs@pathao.com',
                'is_featured' => true,
            ],
            [
                'name' => 'Walton Hi-Tech Industries',
                'slug' => 'walton-hitech',
                'industry' => 'Electronics & Manufacturing',
                'location' => 'Chandra, Gazipur',
                'city' => 'Gazipur',
                'description' => 'Walton is the largest electronics and home appliance manufacturing giant in Bangladesh with global export footprint.',
                'website' => 'https://waltonbd.com',
                'email' => 'recruitment@waltonbd.com',
                'is_featured' => true,
            ],
            [
                'name' => 'Grameenphone Ltd.',
                'slug' => 'grameenphone',
                'industry' => 'Telecommunications',
                'location' => 'Bashundhara, Dhaka',
                'city' => 'Dhaka',
                'description' => 'Grameenphone is the largest telecommunications network operator in Bangladesh, pioneering 5G and digital services.',
                'website' => 'https://grameenphone.com',
                'email' => 'career@grameenphone.com',
                'is_featured' => true,
            ],
            [
                'name' => 'Square Pharmaceuticals PLC',
                'slug' => 'square-pharma',
                'industry' => 'Pharmaceuticals & Healthcare',
                'location' => 'Uttara, Dhaka',
                'city' => 'Dhaka',
                'description' => 'Square Pharmaceuticals is the pioneer and market leader in the Bangladesh pharmaceutical industry.',
                'website' => 'https://squarepharma.com.bd',
                'email' => 'hr@squarepharma.com.bd',
                'is_featured' => true,
            ],
            [
                'name' => 'Chaldal Limited',
                'slug' => 'chaldal',
                'industry' => 'E-Commerce & Tech',
                'location' => 'Dhanmondi, Dhaka',
                'city' => 'Dhaka',
                'description' => 'Chaldal is Bangladesh’s premier online grocery delivery platform revolutionizing retail through deep-tech logistics.',
                'website' => 'https://chaldal.com',
                'email' => 'careers@chaldal.com',
                'is_featured' => true,
            ],
            [
                'name' => 'Daraz Bangladesh',
                'slug' => 'daraz-bangladesh',
                'industry' => 'E-Commerce & Retail',
                'location' => 'Tejgaon, Dhaka',
                'city' => 'Dhaka',
                'description' => 'Daraz is the leading e-commerce marketplace in South Asia, connecting thousands of sellers with millions of customers.',
                'website' => 'https://daraz.com.bd',
                'email' => 'jobs@daraz.com.bd',
                'is_featured' => true,
            ],
            [
                'name' => 'BRAC',
                'slug' => 'brac-bangladesh',
                'industry' => 'NGO & Social Development',
                'location' => 'Mohakhali, Dhaka',
                'city' => 'Dhaka',
                'description' => 'BRAC is an international development organization based in Bangladesh, recognized as the world’s leading NGO.',
                'website' => 'https://brac.net',
                'email' => 'recruitment@brac.net',
                'is_featured' => true,
            ],
            [
                'name' => 'ShopUp',
                'slug' => 'shopup',
                'industry' => 'B2B Commerce & Supply Chain',
                'location' => 'Tejgaon, Dhaka',
                'city' => 'Dhaka',
                'description' => 'ShopUp is Bangladesh’s premier full-stack B2B commerce platform helping small neighborhood shops access products and financing.',
                'website' => 'https://shopup.org',
                'email' => 'careers@shopup.org',
                'is_featured' => true,
            ],
        ];

        $companyMap = [];
        foreach ($companiesData as $cData) {
            $user = User::firstOrCreate(
                ['email' => $cData['email']],
                [
                    'name' => $cData['name'] . ' HR',
                    'role' => 'employer',
                    'password' => Hash::make('Password@12345'),
                ]
            );

            $company = Company::firstOrCreate(
                ['slug' => $cData['slug']],
                [
                    'user_id' => $user->id,
                    'name' => $cData['name'],
                    'industry' => $cData['industry'],
                    'location' => $cData['location'],
                    'city' => $cData['city'] ?? 'Dhaka',
                    'description' => $cData['description'],
                    'website' => $cData['website'],
                    'is_featured' => $cData['is_featured'],
                    'verification_status' => 'verified',
                    'is_verified' => true,
                    'allow_job_posting' => true,
                ]
            );
            $company->update([
                'user_id' => $user->id,
                'name' => $cData['name'],
                'industry' => $cData['industry'],
                'location' => $cData['location'],
                'city' => $cData['city'] ?? 'Dhaka',
                'description' => $cData['description'],
                'website' => $cData['website'],
                'is_featured' => $cData['is_featured'],
                'verification_status' => 'verified',
                'is_verified' => true,
                'allow_job_posting' => true,
            ]);
            $companyMap[$cData['slug']] = $company->id;
        }

        // 3. Realistic Jobs across categories and divisions
        $jobsList = [
            [
                'company_slug' => 'brain-station-23',
                'category_name' => 'Software & IT',
                'title' => 'Senior Full Stack Engineer (React & Laravel)',
                'slug' => 'senior-full-stack-engineer-react-laravel',
                'job_type' => 'Full-time',
                'workplace_type' => 'Hybrid',
                'division' => 'Dhaka',
                'district' => 'Dhaka',
                'location' => 'Mohakhali, Dhaka',
                'vacancies' => 3,
                'experience_level' => 'Senior Level',
                'salary_min' => 90000,
                'salary_max' => 140000,
                'salary_range' => 'BDT 90,000 - 140,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Laravel, React, Next.js, MySQL, Redis, AWS, Docker, REST API',
                'job_summary' => 'We are looking for a Senior Full Stack Engineer experienced in Laravel and React to build high-scale enterprise applications.',
                'responsibilities' => "• Architect, develop, and maintain clean and scalable web applications.\n• Collaborate with cross-functional teams including product managers and designers.\n• Optimize database queries, API performance, and caching systems.\n• Conduct code reviews and mentor junior developers.",
                'education_requirements' => 'B.Sc. in Computer Science & Engineering or equivalent practical experience.',
                'experience_requirements' => '4+ years of professional full-stack development experience.',
                'benefits' => "• Two festival bonuses per year.\n• Weekly 2 days off (Fri-Sat).\n• Health & Life Insurance coverage.\n• Subsidized lunch and snacks.",
                'deadline' => now()->addDays(28)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'brain-station-23',
                'category_name' => 'Software & IT',
                'title' => 'Frontend Developer (Next.js & TypeScript)',
                'slug' => 'frontend-developer-nextjs-typescript',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Dhaka',
                'district' => 'Dhaka',
                'location' => 'Mohakhali, Dhaka',
                'vacancies' => 2,
                'experience_level' => 'Mid Level',
                'salary_min' => 60000,
                'salary_max' => 90000,
                'salary_range' => 'BDT 60,000 - 90,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'React, Next.js, TypeScript, Tailwind CSS, Redux, Zustand',
                'job_summary' => 'Join our frontend team to build high-performance, accessible, and responsive user interfaces for global clients.',
                'responsibilities' => "• Implement pixel-perfect, responsive web designs from Figma.\n• Build reusable UI components using Tailwind CSS and Next.js.\n• Ensure cross-browser compatibility and optimized web core vitals.",
                'education_requirements' => 'B.Sc. in CSE / SE or related field.',
                'experience_requirements' => '2-4 years of modern frontend experience with React / Next.js.',
                'benefits' => "• Annual performance appraisal.\n• Friendly work culture with learning allowances.\n• Flexible working hours.",
                'deadline' => now()->addDays(35)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'bkash-limited',
                'category_name' => 'Banking & Finance',
                'title' => 'Product Manager - Digital Financial Services',
                'slug' => 'product-manager-dfs-bkash',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Dhaka',
                'district' => 'Dhaka',
                'location' => 'Gulshan 1, Dhaka',
                'vacancies' => 1,
                'experience_level' => 'Senior Level',
                'salary_min' => 120000,
                'salary_max' => 180000,
                'salary_range' => 'BDT 120,000 - 180,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Product Management, Agile, Fintech, User Research, Data Analytics, Jira',
                'job_summary' => 'Drive the vision, strategy, and execution of next-generation digital payment features for over 70 million customers.',
                'responsibilities' => "• Own end-to-end product roadmap for fintech consumer apps.\n• Define user stories, acceptance criteria, and work closely with engineering teams.\n• Monitor business metrics, transaction volumes, and conversion funnels.",
                'education_requirements' => 'BBA / MBA / B.Sc. from a recognized university.',
                'experience_requirements' => '5+ years in product management or fintech operations.',
                'benefits' => "• Top-tier provident fund & gratuity.\n• Comprehensive family medical insurance.\n• Profit share bonus and annual increment.",
                'deadline' => now()->addDays(30)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'bkash-limited',
                'category_name' => 'Software & IT',
                'title' => 'DevOps & Cloud Security Specialist',
                'slug' => 'devops-cloud-security-specialist',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Dhaka',
                'district' => 'Dhaka',
                'location' => 'Gulshan 1, Dhaka',
                'vacancies' => 2,
                'experience_level' => 'Senior Level',
                'salary_min' => 110000,
                'salary_max' => 160000,
                'salary_range' => 'BDT 110,000 - 160,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Kubernetes, Docker, AWS, CI/CD, Terraform, Linux, Cloud Security',
                'job_summary' => 'Manage mission-critical fintech infrastructure, ensuring 99.99% uptime, compliance, and disaster recovery.',
                'responsibilities' => "• Build and automate CI/CD delivery pipelines.\n• Manage Kubernetes clusters and microservices deployment.\n• Enforce strict security policies and vulnerability patch management.",
                'education_requirements' => 'B.Sc. in Computer Science or Electrical Engineering.',
                'experience_requirements' => '4+ years of DevOps/Cloud engineering experience.',
                'benefits' => "• Corporate transport facility.\n• Excellent work-life balance.\n• Subsidized breakfast and buffet lunch.",
                'deadline' => now()->addDays(25)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'pathao',
                'category_name' => 'Remote & Freelance',
                'title' => 'Customer Success Specialist (Remote)',
                'slug' => 'customer-success-specialist-remote-pathao',
                'job_type' => 'remote',
                'workplace_type' => 'Remote',
                'division' => 'Dhaka',
                'district' => 'Dhaka',
                'location' => 'Remote (Anywhere in Bangladesh)',
                'vacancies' => 5,
                'experience_level' => 'Entry Level',
                'salary_min' => 25000,
                'salary_max' => 38000,
                'salary_range' => 'BDT 25,000 - 38,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Customer Service, Communication, Problem Solving, CRM, Bangla, English',
                'job_summary' => 'Provide top-quality support to Pathao users, riders, and merchant partners via live chat, email, and tickets from home.',
                'responsibilities' => "• Respond promptly and empathetically to user inquiries.\n• Resolve delivery and payment escalations within SLA guidelines.\n• Log user feedback to help improve the Pathao mobile app experience.",
                'education_requirements' => 'Graduation / Ongoing Bachelor degree from any discipline.',
                'experience_requirements' => '0-2 years of relevant experience. Freshers with good English & Bangla skills are encouraged to apply.',
                'benefits' => "• 100% remote job with equipment allowance.\n• Monthly internet bill reimbursement.\n• Performance-based monthly incentives.",
                'deadline' => now()->addDays(40)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'pathao',
                'category_name' => 'Marketing & Sales',
                'title' => 'Growth & Digital Marketing Executive',
                'slug' => 'growth-digital-marketing-executive-pathao',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Dhaka',
                'district' => 'Dhaka',
                'location' => 'Banani, Dhaka',
                'vacancies' => 2,
                'experience_level' => 'Mid Level',
                'salary_min' => 45000,
                'salary_max' => 70000,
                'salary_range' => 'BDT 45,000 - 70,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Meta Ads, Google Ads, SEO, Performance Marketing, Analytics, Copywriting',
                'job_summary' => 'Execute high-impact user acquisition and retention campaigns for Pathao food, courier, and ride services.',
                'responsibilities' => "• Run and optimize paid social and search engine marketing campaigns.\n• Analyze campaign CAC, LTV, and conversion rate metrics.\n• Collaborate with content creators and designers on ad creatives.",
                'education_requirements' => 'BBA in Marketing or related field.',
                'experience_requirements' => '2+ years of hands-on digital marketing experience.',
                'benefits' => "• Pathao ride and food discount credits.\n• Health and hospitalization insurance.\n• Vibrant startup culture.",
                'deadline' => now()->addDays(32)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'walton-hitech',
                'category_name' => 'Engineering',
                'title' => 'Senior Electrical & Electronics Engineer (R&D)',
                'slug' => 'senior-electrical-engineer-walton',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Dhaka',
                'district' => 'Gazipur',
                'location' => 'Chandra, Gazipur',
                'vacancies' => 4,
                'experience_level' => 'Senior Level',
                'salary_min' => 75000,
                'salary_max' => 120000,
                'salary_range' => 'BDT 75,000 - 120,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'PCB Design, Embedded Systems, IoT, C/C++, Microcontroller, Circuit Simulation',
                'job_summary' => 'Innovate and engineer smart home appliances, IoT circuits, and power boards at Walton Hi-Tech R&D headquarters.',
                'responsibilities' => "• Design multilayer PCBs and test prototypes for smart appliances.\n• Collaborate with manufacturing plant teams for mass production testing.\n• Ensure quality compliance with international electrical safety standards.",
                'education_requirements' => 'B.Sc. in EEE (Electrical & Electronics Engineering) from a reputed university.',
                'experience_requirements' => '4-7 years of R&D or electronics design experience.',
                'benefits' => "• Walton residential campus accommodation or transport.\n• 2 Festival bonuses + Profit share bonus.\n• Provident Fund & Gratuity.",
                'deadline' => now()->addDays(45)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'walton-hitech',
                'category_name' => 'Garments & Textile',
                'title' => 'Supply Chain & Procurement Officer',
                'slug' => 'supply-chain-procurement-officer-walton',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Dhaka',
                'district' => 'Gazipur',
                'location' => 'Kaliakair, Gazipur',
                'vacancies' => 2,
                'experience_level' => 'Mid Level',
                'salary_min' => 40000,
                'salary_max' => 65000,
                'salary_range' => 'BDT 40,000 - 65,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Supply Chain, Procurement, Vendor Management, Negotiation, ERP, Excel',
                'job_summary' => 'Oversee raw material procurement, local and foreign vendor coordination, and inventory optimization.',
                'responsibilities' => "• Manage purchase orders, vendor evaluation, and contract negotiation.\n• Coordinate with customs clearing agents and logistics partners.\n• Track factory inventory levels to prevent supply disruption.",
                'education_requirements' => 'BBA / MBA with major in Supply Chain Management or Finance.',
                'experience_requirements' => '2-4 years of procurement experience in manufacturing industry.',
                'benefits' => "• Company bus facility covering Dhaka-Gazipur route.\n• Subsidized factory meals.\n• Festival bonuses.",
                'deadline' => now()->addDays(38)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'square-pharma',
                'category_name' => 'Healthcare & Pharma',
                'title' => 'Medical Promotion Officer (MPO)',
                'slug' => 'medical-promotion-officer-mpo-square',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Chattagram',
                'district' => 'Chattagram',
                'location' => 'Chattagram Sadar, Chattagram',
                'vacancies' => 10,
                'experience_level' => 'Entry Level',
                'salary_min' => 28000,
                'salary_max' => 42000,
                'salary_range' => 'BDT 28,000 - 42,000 / Month + DA',
                'salary_type' => 'Monthly',
                'required_skills' => 'Product Presentation, Doctor Relationship, Medical Detailing, Sales Communication',
                'job_summary' => 'Promote high-quality pharmaceutical formulations to doctors, hospitals, and pharmacies across the assigned territory.',
                'responsibilities' => "• Visit medical practitioners and introduce innovative drug formulations.\n• Achieve territory sales targets and maintain doctor database.\n• Coordinate with distribution depots for timely stock delivery.",
                'education_requirements' => 'Graduate in any science discipline (Science in SSC/HSC preferred).',
                'experience_requirements' => 'Freshers with strong communication are encouraged. Experienced MPOs get higher grade.',
                'benefits' => "• Daily Allowance (DA) and Travel Allowance (TA).\n• Motorcycle allowance and fuel bill.\n• Gratuity and Provident Fund.",
                'deadline' => now()->addDays(30)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'square-pharma',
                'category_name' => 'Healthcare & Pharma',
                'title' => 'Quality Assurance (QA) Executive',
                'slug' => 'qa-executive-square-pharma',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Rajshahi',
                'district' => 'Pabna',
                'location' => 'Salgaria, Pabna',
                'vacancies' => 3,
                'experience_level' => 'Mid Level',
                'salary_min' => 45000,
                'salary_max' => 70000,
                'salary_range' => 'BDT 45,000 - 70,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'cGMP, Quality Assurance, HPLC, Documentation, Batch Review, WHO Guidelines',
                'job_summary' => 'Ensure strict adherence to WHO cGMP standards in manufacturing world-class pharmaceutical products.',
                'responsibilities' => "• Review batch manufacturing records (BMR) and analytical data.\n• Conduct internal audits and investigate deviations or OOS results.\n• Prepare validation protocols and SOPs for modern production lines.",
                'education_requirements' => 'M.Pharm / B.Pharm from a recognized university.',
                'experience_requirements' => '2-4 years of experience in pharmaceutical QA/QC.',
                'benefits' => "• Subsidized residential quarters inside company township.\n• 2 Festival bonuses + Annual profit share.\n• Group life insurance.",
                'deadline' => now()->addDays(29)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'grameenphone',
                'category_name' => 'Telecommunication',
                'title' => 'Network Operations & 5G Infrastructure Engineer',
                'slug' => 'network-operations-5g-engineer-gp',
                'job_type' => 'Full-time',
                'workplace_type' => 'Hybrid',
                'division' => 'Dhaka',
                'district' => 'Dhaka',
                'location' => 'GPHouse, Bashundhara, Dhaka',
                'vacancies' => 2,
                'experience_level' => 'Mid Level',
                'salary_min' => 85000,
                'salary_max' => 135000,
                'salary_range' => 'BDT 85,000 - 135,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Telecom, 4G/5G Core, IP Routing, CCNA, Optical Transmission, NOC Operations',
                'job_summary' => 'Maintain and upgrade the country’s premier nationwide mobile network infrastructure.',
                'responsibilities' => "• Monitor nationwide telecom core networks and resolve incident alerts.\n• Support 5G rollout and fiber-optic backbone capacity enhancement.\n• Coordinate with field engineering teams for rapid outage resolution.",
                'education_requirements' => 'B.Sc. in EEE / ETE / CSE.',
                'experience_requirements' => '3+ years in telecom operations or network engineering.',
                'benefits' => "• State-of-the-art hybrid work environment at GPHouse.\n• World-class medical insurance for family.\n• Annual performance bonuses and mobile allowances.",
                'deadline' => now()->addDays(33)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'daraz-bangladesh',
                'category_name' => 'Design & Creative',
                'title' => 'Senior UI/UX & Brand Visual Designer',
                'slug' => 'senior-ui-ux-designer-daraz',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Dhaka',
                'district' => 'Dhaka',
                'location' => 'Tejgaon I/A, Dhaka',
                'vacancies' => 2,
                'experience_level' => 'Senior Level',
                'salary_min' => 70000,
                'salary_max' => 110000,
                'salary_range' => 'BDT 70,000 - 110,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Figma, Adobe XD, UI/UX Design, Design Systems, Mobile Apps, Prototyping',
                'job_summary' => 'Design captivating user journeys and marketing campaign interfaces for Bangladesh’s largest online mega-campaigns.',
                'responsibilities' => "• Build intuitive user flows, wireframes, and prototypes for Daraz App & Web.\n• Maintain and expand the brand design system and UI library.\n• Work directly with product managers and engineers during sprint delivery.",
                'education_requirements' => 'Graduate in Graphic Design, Fine Arts, CSE, or equivalent portfolio experience.',
                'experience_requirements' => '3+ years in UI/UX or product design.',
                'benefits' => "• Daraz shopping vouchers and campaign perks.\n• Top health insurance coverage.\n• Modern open-space creative studio.",
                'deadline' => now()->addDays(27)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'chaldal',
                'category_name' => 'Remote & Freelance',
                'title' => 'Content Writer & Copywriter (Remote)',
                'slug' => 'content-writer-copywriter-chaldal-remote',
                'job_type' => 'remote',
                'workplace_type' => 'Remote',
                'division' => 'Dhaka',
                'district' => 'Dhaka',
                'location' => 'Remote (Work from Home)',
                'vacancies' => 3,
                'experience_level' => 'Mid Level',
                'salary_min' => 32000,
                'salary_max' => 50000,
                'salary_range' => 'BDT 32,000 - 50,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Content Writing, Copywriting, SEO, Social Media, Creative Writing, English & Bangla',
                'job_summary' => 'Craft engaging product descriptions, push notifications, email newsletters, and blog posts from anywhere in Bangladesh.',
                'responsibilities' => "• Write catchy copy for in-app banners, SMS, and promotional campaigns.\n• Produce SEO-optimized articles for blog and organic search growth.\n• Coordinate with the brand marketing team on seasonal festive campaigns.",
                'education_requirements' => 'Bachelor’s degree in English, Journalism, Marketing, or related field.',
                'experience_requirements' => '1-3 years of proven content writing or copywriting experience.',
                'benefits' => "• 100% remote flexibility with home office support.\n• Monthly grocery discounts on Chaldal.\n• Festival bonuses.",
                'deadline' => now()->addDays(36)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'shopup',
                'category_name' => 'Banking & Finance',
                'title' => 'Senior Accounts & Financial Analyst',
                'slug' => 'senior-accounts-financial-analyst-shopup',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Dhaka',
                'district' => 'Dhaka',
                'location' => 'Tejgaon, Dhaka',
                'vacancies' => 2,
                'experience_level' => 'Senior Level',
                'salary_min' => 70000,
                'salary_max' => 105000,
                'salary_range' => 'BDT 70,000 - 105,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Accounting, Financial Modeling, Budgeting, Tax, Audit, QuickBooks, Excel',
                'job_summary' => 'Manage corporate financial reporting, balance sheet reconciliations, cash flow modeling, and statutory tax compliance.',
                'responsibilities' => "• Prepare monthly, quarterly, and annual financial statements.\n• Supervise accounts payable and receivable operations across distribution hubs.\n• Assist in external audit preparations and corporate income tax filings.",
                'education_requirements' => 'BBA/MBA in Accounting/Finance, CA (CC) / CMA / ACCA partly qualified.',
                'experience_requirements' => '4+ years of relevant accounting and financial management experience.',
                'benefits' => "• Competitive compensation with annual review.\n• Health and life insurance.\n• Complimentary office lunch and evening snacks.",
                'deadline' => now()->addDays(24)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
            [
                'company_slug' => 'brac-bangladesh',
                'category_name' => 'Education & Training',
                'title' => 'Project Coordinator - Education & Youth Empowerment',
                'slug' => 'project-coordinator-education-brac',
                'job_type' => 'Full-time',
                'workplace_type' => 'On-site',
                'division' => 'Sylhet',
                'district' => 'Sylhet',
                'location' => 'Sylhet Sadar, Sylhet',
                'vacancies' => 2,
                'experience_level' => 'Mid Level',
                'salary_min' => 50000,
                'salary_max' => 75000,
                'salary_range' => 'BDT 50,000 - 75,000 / Month',
                'salary_type' => 'Monthly',
                'required_skills' => 'Project Management, Community Engagement, Training, Report Writing, NGO Operations',
                'job_summary' => 'Lead field implementation of community education initiatives and digital literacy programs across Sylhet division.',
                'responsibilities' => "• Supervise field trainers, learning centers, and community mobilizers.\n• Coordinate with local government officials, schools, and youth clubs.\n• Prepare monthly progress reports and donor impact documentation.",
                'education_requirements' => 'Masters in Social Sciences, Development Studies, Education, or related discipline.',
                'experience_requirements' => '3+ years in development sector or project management.',
                'benefits' => "• Provident Fund, Gratuity, and Festival Allowance.\n• Medical insurance coverage for employee and dependents.\n• Maternity/Paternity leave and travel allowances.",
                'deadline' => now()->addDays(31)->toDateString(),
                'is_active' => true,
                'is_remote_project' => false,
            ],
        ];

        foreach ($jobsList as $j) {
            $companyId = $companyMap[$j['company_slug']] ?? null;
            $categoryId = $catMap[$j['category_name']] ?? null;

            if (!$companyId || !$categoryId) continue;

            Job::updateOrCreate(
                ['slug' => $j['slug']],
                [
                    'company_id' => $companyId,
                    'category_id' => $categoryId,
                    'title' => $j['title'],
                    'slug' => $j['slug'],
                    'job_type' => $j['job_type'],
                    'workplace_type' => $j['workplace_type'],
                    'division' => $j['division'],
                    'district' => $j['district'],
                    'location' => $j['location'],
                    'vacancies' => $j['vacancies'],
                    'experience_level' => $j['experience_level'],
                    'salary_min' => $j['salary_min'],
                    'salary_max' => $j['salary_max'],
                    'salary_range' => $j['salary_range'],
                    'salary_type' => $j['salary_type'],
                    'required_skills' => $j['required_skills'],
                    'description' => $j['job_summary'] . "\n\nResponsibilities:\n" . $j['responsibilities'] . "\n\nRequirements:\n" . $j['education_requirements'] . " " . $j['experience_requirements'],
                    'job_summary' => $j['job_summary'],
                    'responsibilities' => $j['responsibilities'],
                    'education_requirements' => $j['education_requirements'],
                    'experience_requirements' => $j['experience_requirements'],
                    'benefits' => $j['benefits'],
                    'deadline' => $j['deadline'],
                    'is_active' => $j['is_active'],
                    'is_remote_project' => $j['is_remote_project'],
                ]
            );
        }

        // 4. Ensure all 50 CV templates are active
        CvTemplate::query()->update(['is_active' => true]);

        // 5. Clear caches so homepage and job filters reflect fresh data immediately
        try {
            Cache::forget('homepage_data_v1');
            Cache::forget('homepage_settings_v1');
            Cache::flush();
        } catch (\Throwable $e) {}
    }

    public function down(): void
    {
        // Safe reversible migration
    }
};
